config/routes.rb
Rails.application.routes.draw do
  get 'ticket/index'
  root to: 'ticket#index'

  resources :tickets do
    get 'bought', to: 'ticket#bought', as: :bought
    get 'mistake', to: 'ticket#mistake', as: :mistake
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ticket_controller.rb
class TicketController < ApplicationController
  def index
    if Ticket.first
      @ticket = Ticket.first
    else
      @ticket = Ticket.new
      @ticket.sum = 0
      @ticket.share = 0
      @ticket.normal = 0
      @ticket.discount = 0

      if @ticket.save
        redirect_to root_path
      end
    end
  end

  def bought
    @ticket = Ticket.first
    @price = params[:price].to_i
    @ticket.sum = @ticket.sum + @price

    # Ticket counter
    if @price == 400
      @ticket.share = @ticket.share + 1
    elsif @price == 500
      @ticket.normal = @ticket.normal + 1
    elsif @price == 300
      @ticket.discount = @ticket.discount + 1
    end

    if @ticket.save
      redirect_to root_path
    end
  end

  def mistake
    @ticket = Ticket.first
    @price = params[:price].to_i

    # Ticket counter
    if @price == 400
      @ticket.share = @ticket.share - 1
    elsif @price == 500
      @ticket.normal = @ticket.normal - 1
    elsif @price == 300
      @ticket.discount = @ticket.discount - 1
    end 

    @ticket.sum = @ticket.sum - @price
    if @ticket.save
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketCounter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ticket/index.html.erb
<div class='appWrapper'>
    <div class='earnings'><%= @ticket.sum %>₽ (<%= @ticket.share + @ticket.normal%>)</div>
    <div class='ticketsWrapper'>
        <div class='ticket'>
            <span class='price'>400₽ (<%= @ticket.share%>)</span>
            <%= link_to '+', ticket_bought_path(@ticket, :price => 400), class:'ticketBought'%>
            <%= link_to '-', ticket_mistake_path(@ticket, :price => 400), class:'ticketMistake'%>
        </div>
        <div class='ticket'>
            <span class='price'>500₽ (<%= @ticket.normal%>)</span>
            <%= link_to '+', ticket_bought_path(@ticket, :price => 500), class:'ticketBought'%>
            <%= link_to '-', ticket_mistake_path(@ticket, :price => 500), class:'ticketMistake'%>
        </div><div class='ticket'>
            <span class='price'>300₽ (<%= @ticket.discount%>)</span>
            <%= link_to '+', ticket_bought_path(@ticket, :price => 300), class:'ticketBought'%>
            <%= link_to '-', ticket_mistake_path(@ticket, :price => 300), class:'ticketMistake'%>
        </div>
    </div>
<div>